"use client";
import Link from "next/link";
import { useStore } from "@/context/StoreContext";

export default function Cart() {
  const { cart, change, remove, cartTotal } = useStore();
  const shipping = cartTotal >= 349 || cartTotal === 0 ? 0 : 49;
  return <div className="container py-12 md:py-16"><p className="eyebrow">Your basket</p><h1 className="section-heading mt-3">Good food starts here.</h1>{!cart.length ? <div className="mt-10 border border-[#eadfd2] bg-[#fffdf8] px-6 py-20 text-center"><p className="text-5xl">🧺</p><p className="mt-5 text-xl font-bold">Your basket is empty.</p><p className="mt-2 text-[#75665d]">Add a little spice to your next meal.</p><Link className="button-primary mt-6 inline-block rounded-full px-6 py-3 font-bold" href="/collections/masala-powders">Shop spices</Link></div> : <div className="mt-10 grid gap-8 lg:grid-cols-[1fr_380px]"><div className="border border-[#eadfd2] bg-[#fffdf8] p-4 sm:p-6">{cart.map((item) => <div className="grid grid-cols-[1fr_auto] gap-4 border-b border-[#eadfd2] py-5 first:pt-0 last:border-0 last:pb-0 sm:grid-cols-[1fr_auto_auto_auto] sm:items-center" key={`${item.id}-${item.packSize}`}><div><p className="font-bold">{item.name}</p><p className="mt-1 text-sm text-[#75665d]">{item.packSize} · ₹{item.price} each</p></div><div className="flex items-center gap-3 rounded-full border border-[#eadfd2] px-2 py-1"><button aria-label={`Decrease ${item.name}`} onClick={() => change(item.id, item.quantity - 1, item.packSize)} className="px-2 text-lg">−</button><span className="min-w-4 text-center text-sm">{item.quantity}</span><button aria-label={`Increase ${item.name}`} onClick={() => change(item.id, item.quantity + 1, item.packSize)} className="px-2 text-lg">+</button></div><b className="text-right text-[#8f2635]">₹{item.price * item.quantity}</b><button aria-label={`Remove ${item.name}`} onClick={() => remove(item.id, item.packSize)} className="justify-self-end text-sm text-[#75665d] underline underline-offset-4">Remove</button></div>)}</div><aside className="h-fit border border-[#eadfd2] bg-[#fffdf8] p-6"><p className="eyebrow">Summary</p><h2 className="serif mt-2 text-3xl font-bold text-[#8f2635]">Order total</h2><p className="mt-6 flex justify-between text-[#75665d]">Subtotal <b className="text-[#2e241f]">₹{cartTotal}</b></p><p className="mt-3 flex justify-between text-[#75665d]">Shipping <b className="text-[#2e241f]">{shipping ? "₹49" : "Free"}</b></p><hr className="my-5 border-[#eadfd2]"/><p className="flex justify-between text-lg font-bold">Total <b className="text-[#8f2635]">₹{cartTotal + shipping}</b></p><p className="mt-5 bg-[#f3e5d3] p-3 text-sm text-[#75665d]">{cartTotal < 349 ? `Add ₹${349 - cartTotal} more for free delivery.` : "You unlocked free delivery."}</p><Link className="button-primary mt-5 block rounded-full p-3 text-center font-bold" href="/checkout">Proceed to checkout</Link><Link className="mt-4 block text-center text-sm font-semibold text-[#8f2635] underline underline-offset-4" href="/collections/masala-powders">Continue shopping</Link></aside></div>}</div>;
}
