"use client";
import { useEffect, useState } from "react";
import Link from "next/link";
import { API_URL } from "@/lib/api";
type Product = { id: number; name: string; category_name: string; price: string; stock_quantity: number; is_active: number };
export default function AdminProducts() {
  const [products, setProducts] = useState<Product[]>([]); const [error, setError] = useState("");
  async function load() { const token = localStorage.getItem("ar-admin-token"); const response = await fetch(`${API_URL}/api/products?includeInactive=true`, { headers: { Authorization: `Bearer ${token}` } }); if (!response.ok) throw new Error("Unable to load products"); setProducts(await response.json()); }
  useEffect(() => { const token = localStorage.getItem("ar-admin-token"); fetch(`${API_URL}/api/products?includeInactive=true`, { headers: { Authorization: `Bearer ${token}` } }).then(async (response) => { if (!response.ok) throw new Error("Unable to load products"); return response.json(); }).then(setProducts).catch((loadError) => setError(loadError.message)); }, []);
  async function deactivate(id: number) { const token = localStorage.getItem("ar-admin-token"); const response = await fetch(`${API_URL}/api/products/${id}`, { method: "DELETE", headers: { Authorization: `Bearer ${token}` } }); if (!response.ok) { setError("Unable to deactivate product"); return; } load().catch((loadError) => setError(loadError.message)); }
  return <main className="container py-12"><Link href="/admin" className="text-sm underline">← Dashboard</Link><h1 className="serif mt-4 text-5xl font-bold text-[#7d1f2b]">Products</h1>{error&&<p role="alert" className="mt-4 text-red-700">{error}</p>}<div className="mt-8 overflow-x-auto rounded-2xl bg-white"><table className="w-full text-left text-sm"><thead><tr className="border-b"><th className="p-4">Name</th><th className="p-4">Category</th><th className="p-4">Price</th><th className="p-4">Stock</th><th className="p-4">Status</th><th className="p-4">Action</th></tr></thead><tbody>{products.map((product)=><tr className="border-b last:border-0" key={product.id}><td className="p-4 font-semibold">{product.name}</td><td className="p-4">{product.category_name}</td><td className="p-4">₹{product.price}</td><td className={`p-4 ${product.stock_quantity<=5?"font-bold text-red-700":""}`}>{product.stock_quantity}</td><td className="p-4">{product.is_active?"Active":"Inactive"}</td><td className="p-4"><button disabled={!product.is_active} onClick={()=>deactivate(product.id)} className="rounded-full border px-3 py-1 disabled:opacity-40">Deactivate</button></td></tr>)}</tbody></table></div></main>;
}
