"use client";
import { useEffect, useState } from "react";
import Link from "next/link";
import { API_URL } from "@/lib/api";
type Order = { id: number; order_number: string; customer_name: string; total_amount: string; status: string; created_at: string };
export default function AdminOrders() {
  const [orders, setOrders] = useState<Order[]>([]); const [error, setError] = useState("");
  async function load() { const token = localStorage.getItem("ar-admin-token"); const response = await fetch(`${API_URL}/api/admin/orders`, { headers: { Authorization: `Bearer ${token}` } }); if (!response.ok) throw new Error("Unable to load orders"); setOrders(await response.json()); }
  useEffect(() => { const token = localStorage.getItem("ar-admin-token"); fetch(`${API_URL}/api/admin/orders`, { headers: { Authorization: `Bearer ${token}` } }).then(async (response) => { if (!response.ok) throw new Error("Unable to load orders"); return response.json(); }).then(setOrders).catch((loadError) => setError(loadError.message)); }, []);
  async function update(id: number, status: string) { const token = localStorage.getItem("ar-admin-token"); const response = await fetch(`${API_URL}/api/admin/orders/${id}/status`, { method: "PATCH", headers: { "Content-Type": "application/json", Authorization: `Bearer ${token}` }, body: JSON.stringify({ status }) }); if (!response.ok) { setError("Unable to update status"); return; } load().catch((loadError) => setError(loadError.message)); }
  return <main className="container py-12"><Link href="/admin" className="text-sm underline">← Dashboard</Link><h1 className="serif mt-4 text-5xl font-bold text-[#7d1f2b]">Orders</h1>{error&&<p role="alert" className="mt-4 text-red-700">{error}</p>}<div className="mt-8 overflow-x-auto rounded-2xl bg-white"><table className="w-full text-left text-sm"><thead><tr className="border-b"><th className="p-4">Order</th><th className="p-4">Customer</th><th className="p-4">Total</th><th className="p-4">Date</th><th className="p-4">Status</th></tr></thead><tbody>{orders.map((order)=><tr className="border-b last:border-0" key={order.id}><td className="p-4 font-semibold">{order.order_number}</td><td className="p-4">{order.customer_name}</td><td className="p-4">₹{order.total_amount}</td><td className="p-4">{new Date(order.created_at).toLocaleDateString()}</td><td className="p-4"><select value={order.status} onChange={(event)=>update(order.id,event.target.value)} className="rounded-lg border p-2">{["Placed","Confirmed","Shipped","Delivered","Cancelled"].map((status)=><option key={status}>{status}</option>)}</select></td></tr>)}</tbody></table></div></main>;
}
